'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'de' | 'fr' | 'es' | 'it' | 'sk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Language configuration with flags
export const languageConfig: Record<Language, { name: string; flag: string }> = {
  en: { name: 'English', flag: '🇬🇧' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  fr: { name: 'Français', flag: '🇫🇷' },
  es: { name: 'Español', flag: '🇪🇸' },
  it: { name: 'Italiano', flag: '🇮🇹' },
  sk: { name: 'Slovenčina', flag: '🇸🇰' },
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'nav.brands': 'Brands',
    'nav.cart': 'Cart',
    'nav.account': 'Account',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.myOrders': 'My Orders',
    'nav.trackOrder': 'Track Order',
    'nav.signIn': 'Sign In',
    
    // Hero
    'hero.title': 'Premium Telecom Products',
    'hero.subtitle': 'Discover the latest smartphones, tablets, and accessories from top brands',
    'hero.cta': 'Shop Now',
    'hero.secondary': 'View Categories',
    'hero.newArrivals': 'New Arrivals Available',
    'hero.freeShipping': 'Free Shipping',
    'hero.warranty': '2 Year Warranty',
    'hero.securePayment': 'Secure Payment',
    'hero.support': '24/7 Support',
    
    // Products
    'products.title': 'Products',
    'products.featured': 'Featured Products',
    'products.featuredSubtitle': 'Top picks from our collection',
    'products.viewAll': 'View All Products',
    'products.all': 'All Products',
    'products.search': 'Search products...',
    'products.filter': 'Filter',
    'products.sort': 'Sort by',
    'products.sortPrice': 'Price',
    'products.sortName': 'Name',
    'products.sortNewest': 'Newest',
    'products.asc': 'Low to High',
    'products.desc': 'High to Low',
    'products.inStock': 'In Stock',
    'products.outOfStock': 'Out of Stock',
    'products.lowStock': 'Low Stock',
    'products.addToCart': 'Add to Cart',
    'products.viewDetails': 'View Details',
    'products.quickView': 'Quick View',
    'products.noProducts': 'No products found',
    'products.clearFilters': 'Clear Filters',
    'products.priceRange': 'Price Range',
    'products.color': 'Color',
    'products.storage': 'Storage',
    'products.ram': 'RAM',
    'products.category': 'Category',
    'products.brand': 'Brand',
    'products.specifications': 'Specifications',
    'products.description': 'Description',
    'products.relatedProducts': 'Related Products',
    'products.sku': 'SKU',
    'products.warranty': 'Warranty',
    'products.months': 'months',
    'products.month': 'Month',
    'products.loginToViewPrice': 'Login to view price',
    'products.fastDelivery': 'Fast Delivery',
    'products.securePayment': 'Secure Payment',
    'products.easyReturns': 'Easy Returns',
    'products.signInForPricing': 'Sign in to see exclusive pricing and offers',
    'products.loginToBuy': 'Login to Purchase',
    
    // Categories
    'categories.title': 'Categories',
    'categories.shopBy': 'Shop by Category',
    'categories.subtitle': 'Find exactly what you\'re looking for',
    'categories.productsCount': 'products',
    
    // Brands
    'brands.title': 'Brands',
    'brands.shopBy': 'Shop by Brand',
    'brands.subtitle': 'Explore products from top brands',
    'brands.viewAll': 'View All Brands',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.continueShopping': 'Continue Shopping',
    'cart.subtotal': 'Subtotal',
    'cart.tax': 'Tax',
    'cart.shipping': 'Shipping',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.remove': 'Remove',
    'cart.quantity': 'Quantity',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.shipping': 'Shipping Information',
    'checkout.billing': 'Billing Information',
    'checkout.payment': 'Payment Method',
    'checkout.review': 'Review Order',
    'checkout.sameAsBilling': 'Same as billing address',
    'checkout.placeOrder': 'Place Order',
    'checkout.orderNotes': 'Order Notes',
    'checkout.firstName': 'First Name',
    'checkout.lastName': 'Last Name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone',
    'checkout.company': 'Company (Optional)',
    'checkout.address': 'Address',
    'checkout.addressLine2': 'Apartment, suite, etc.',
    'checkout.city': 'City',
    'checkout.state': 'State/Province',
    'checkout.postalCode': 'Postal Code',
    'checkout.country': 'Country',
    'checkout.creditCard': 'Credit Card',
    'checkout.paypal': 'PayPal',
    'checkout.bankTransfer': 'Bank Transfer',
    'checkout.orderSummary': 'Order Summary',
    'checkout.contactInformation': 'Contact Information',
    'checkout.addressLine1': 'Address Line 1',
    'checkout.addressLine2Optional': 'Address Line 2 (Optional)',
    'checkout.taxVat': 'Tax (VAT)',
    'checkout.phoneOptional': 'Phone (Optional)',
    'checkout.stateOptional': 'State/Province (Optional)',
    'checkout.billingAddress': 'Billing Address',
    'checkout.shippingAddress': 'Shipping Address',
    'checkout.sameAsShipping': 'Same as shipping address',
    
    // Orders
    'orders.title': 'My Orders',
    'orders.track': 'Track Order',
    'orders.orderNumber': 'Order Number',
    'orders.date': 'Date',
    'orders.status': 'Status',
    'orders.total': 'Total',
    'orders.details': 'View Details',
    'orders.trackPlaceholder': 'Enter your order number',
    'orders.emailPlaceholder': 'Enter your email',
    'orders.trackButton': 'Track Order',
    'orders.noOrders': 'No orders found',
    'orders.search': 'Search orders...',
    'orders.allStatus': 'All Status',
    'orders.placedOn': 'Placed on',
    'orders.items': 'item(s)',
    'orders.startShopping': 'Start Shopping',
    'orders.tryAdjusting': 'Try adjusting your search or filters',
    'orders.noOrdersYet': "You haven't placed any orders yet",
    
    // Order Status
    'status.pending': 'Pending',
    'status.processing': 'Processing',
    'status.shipped': 'Shipped',
    'status.delivered': 'Delivered',
    'status.cancelled': 'Cancelled',
    
    // Payment Status
    'payment.pending': 'Payment Pending',
    'payment.paid': 'Paid',
    'payment.failed': 'Payment Failed',
    'payment.refunded': 'Refunded',
    
    // Account
    'account.title': 'My Account',
    'account.profile': 'Profile',
    'account.settings': 'Settings',
    'account.profileInformation': 'Profile Information',
    'account.editProfile': 'Edit Profile',
    'account.saveChanges': 'Save Changes',
    'account.cancel': 'Cancel',
    'account.verifiedAccount': 'Verified Account',
    'account.firstName': 'First Name',
    'account.lastName': 'Last Name',
    'account.email': 'Email Address',
    'account.phone': 'Phone Number',
    'account.notProvided': 'Not provided',
    'account.myOrders': 'My Orders',
    'account.trackOrders': 'Track and manage your orders',
    'account.addresses': 'Addresses',
    'account.manageAddresses': 'Manage delivery addresses',
    'account.accountSettings': 'Account Settings',
    'account.preferences': 'Account preferences and security',
    'account.signOut': 'Sign Out',
    'account.logoutDescription': 'Log out of your account',
    'account.viewOrders': 'View your orders',
    'account.signInToView': 'Sign in to see your order history and track shipments',
    'account.signInToAccount': 'Sign in to your account',
    'account.accessAccount': 'Access your orders, wishlist, and account settings',
    'account.createAccount': 'Create Account',
    'account.signInRequired': 'Sign in required',
    
    // Addresses
    'addresses.title': 'My Addresses',
    'addresses.subtitle': 'Manage your delivery addresses',
    'addresses.addNew': 'Add Address',
    'addresses.edit': 'Edit Address',
    'addresses.name': 'Address Name',
    'addresses.namePlaceholder': 'e.g., Home, Office',
    'addresses.street': 'Street Address',
    'addresses.streetPlaceholder': 'Enter street address',
    'addresses.city': 'City',
    'addresses.cityPlaceholder': 'Enter city',
    'addresses.postalCode': 'Postal Code',
    'addresses.postalCodePlaceholder': 'Enter postal code',
    'addresses.country': 'Country',
    'addresses.countryPlaceholder': 'Enter country',
    'addresses.selectCountry': 'Select country',
    'addresses.state': 'State/Region',
    'addresses.selectState': 'Select state/region',
    'addresses.selectCity': 'Select city',
    'addresses.default': 'Default',
    'addresses.setDefault': 'Set as default',
    'addresses.noAddresses': 'No addresses saved',
    'addresses.noAddressesDesc': 'Add your first delivery address to make checkout faster.',
    'addresses.addFirst': 'Add your first address',
    'addresses.updated': 'Address updated',
    'addresses.updatedDesc': 'Your address has been updated successfully.',
    'addresses.added': 'Address added',
    'addresses.addedDesc': 'Your new address has been saved.',
    'addresses.deleted': 'Address deleted',
    'addresses.deletedDesc': 'Your address has been removed.',
    'addresses.defaultSet': 'Default address set',
    'addresses.defaultSetDesc': 'This address will be used as your default delivery address.',
    'addresses.deleteConfirm': 'Delete this address?',
    'addresses.deleteConfirmDesc': 'This action cannot be undone.',
    
    // Settings
    'settings.title': 'Account Settings',
    'settings.subtitle': 'Manage your account preferences',
    'settings.changePassword': 'Change Password',
    'settings.changePasswordDesc': 'Update your password to keep your account secure.',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',
    'settings.updatePassword': 'Update Password',
    'settings.passwordChanged': 'Password changed',
    'settings.passwordChangedDesc': 'Your password has been updated successfully.',
    'settings.passwordMismatch': 'Passwords do not match',
    'settings.passwordMismatchDesc': 'Please make sure your passwords match.',
    'settings.passwordTooShort': 'Password too short',
    'settings.passwordTooShortDesc': 'Password must be at least 8 characters.',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Choose what notifications you receive.',
    'settings.orderUpdates': 'Order Updates',
    'settings.orderUpdatesDesc': 'Get notified about your order status.',
    'settings.promotions': 'Promotions',
    'settings.promotionsDesc': 'Receive promotional offers and discounts.',
    'settings.newsletter': 'Newsletter',
    'settings.newsletterDesc': 'Stay updated with our latest news.',
    'settings.language': 'Language',
    'settings.languageDesc': 'Choose your preferred language.',
    'settings.dangerZone': 'Danger Zone',
    'settings.dangerZoneDesc': 'Irreversible actions for your account.',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteConfirm': 'Are you sure?',
    'settings.deleteConfirmDesc': 'This will permanently delete your account and all associated data. This action cannot be undone.',
    'settings.accountDeleted': 'Account deleted',
    'settings.accountDeletedDesc': 'Your account has been permanently deleted.',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Create Account',
    'auth.createAccount': 'Create Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.welcomeBack': 'Welcome Back',
    'auth.loginSubtitle': 'Login to your account to continue shopping',
    'auth.registerSubtitle': 'Join TeleTrade Hub and start shopping',
    'auth.loginSuccess': 'Login successful!',
    'auth.loginFailed': 'Login failed. Please try again.',
    'auth.registerSuccess': 'Account created successfully!',
    'auth.registerFailed': 'Registration failed. Please try again.',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'John Doe',
    'auth.phone': 'Phone',
    'auth.phonePlaceholder': '+1 234 567 8900',
    'auth.rememberMe': 'Remember me',
    'auth.passwordRequirements': 'Password requirements:',
    'auth.passwordMinLength': 'At least 8 characters',
    'auth.passwordUppercase': 'One uppercase letter',
    'auth.passwordLowercase': 'One lowercase letter',
    'auth.passwordNumber': 'One number',
    'auth.passwordSpecial': 'One special character',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.retry': 'Retry',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.viewAll': 'View All',
    'common.optional': '(Optional)',
    
    // Home
    'home.productsAvailable': 'Products Available',
    'home.topBrands': 'Top Brands',
    'home.customerSupport': 'Customer Support',
    'home.support': 'Support Available',
    'home.authenticProducts': 'Authentic Products',
    'home.securePayments': 'Secure Payments',
    'home.ctaTitle': 'Ready to upgrade your tech?',
    'home.ctaSubtitle': 'Browse our extensive collection of premium telecommunication products from the world\'s leading brands.',
    'home.startShopping': 'Start Shopping',
    
    // Footer
    'footer.about': 'About Us',
    'footer.contact': 'Contact',
    'footer.howToBuy': 'How to Buy',
    'footer.shipping': 'Shipping Policy',
    'footer.returns': 'Returns Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.copyright': '© 2026 TeleTrade Hub. All rights reserved.',
    'footer.description': 'Your trusted partner for premium telecommunication products. Quality devices from the world\'s top brands.',
    'footer.company': 'Company',
    'footer.policies': 'Policies',
    'footer.secureCheckout': 'Secure Checkout',
    'footer.safePayment': 'Safe Payment',
    'footer.fastDelivery': 'Fast Delivery',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.products': 'Produkte',
    'nav.categories': 'Kategorien',
    'nav.brands': 'Marken',
    'nav.cart': 'Warenkorb',
    'nav.account': 'Konto',
    'nav.login': 'Anmelden',
    'nav.register': 'Registrieren',
    'nav.logout': 'Abmelden',
    'nav.myOrders': 'Meine Bestellungen',
    'nav.trackOrder': 'Bestellung verfolgen',
    'nav.signIn': 'Anmelden',
    
    // Hero
    'hero.title': 'Premium Telekom Produkte',
    'hero.subtitle': 'Entdecken Sie die neuesten Smartphones, Tablets und Zubehör von Top-Marken',
    'hero.cta': 'Jetzt Einkaufen',
    'hero.secondary': 'Kategorien ansehen',
    'hero.newArrivals': 'Neue Artikel verfügbar',
    'hero.freeShipping': 'Kostenloser Versand',
    'hero.warranty': '2 Jahre Garantie',
    'hero.securePayment': 'Sichere Zahlung',
    'hero.support': '24/7 Support',
    
    // Products
    'products.title': 'Produkte',
    'products.featured': 'Empfohlene Produkte',
    'products.featuredSubtitle': 'Top-Auswahl aus unserer Sammlung',
    'products.viewAll': 'Alle Produkte ansehen',
    'products.all': 'Alle Produkte',
    'products.search': 'Produkte suchen...',
    'products.filter': 'Filtern',
    'products.sort': 'Sortieren nach',
    'products.sortPrice': 'Preis',
    'products.sortName': 'Name',
    'products.sortNewest': 'Neueste',
    'products.asc': 'Aufsteigend',
    'products.desc': 'Absteigend',
    'products.inStock': 'Auf Lager',
    'products.outOfStock': 'Nicht verfügbar',
    'products.lowStock': 'Wenig Bestand',
    'products.addToCart': 'In den Warenkorb',
    'products.viewDetails': 'Details ansehen',
    'products.quickView': 'Schnellansicht',
    'products.noProducts': 'Keine Produkte gefunden',
    'products.clearFilters': 'Filter löschen',
    'products.priceRange': 'Preisbereich',
    'products.color': 'Farbe',
    'products.storage': 'Speicher',
    'products.ram': 'RAM',
    'products.category': 'Kategorie',
    'products.brand': 'Marke',
    'products.specifications': 'Spezifikationen',
    'products.description': 'Beschreibung',
    'products.relatedProducts': 'Ähnliche Produkte',
    'products.sku': 'Artikelnummer',
    'products.warranty': 'Garantie',
    'products.months': 'Monate',
    'products.month': 'Monat',
    'products.loginToViewPrice': 'Anmelden für Preise',
    'products.fastDelivery': 'Schnelle Lieferung',
    'products.securePayment': 'Sichere Zahlung',
    'products.easyReturns': 'Einfache Rückgabe',
    'products.signInForPricing': 'Melden Sie sich an, um exklusive Preise zu sehen',
    'products.loginToBuy': 'Zum Kaufen anmelden',
    
    // Categories
    'categories.title': 'Kategorien',
    'categories.shopBy': 'Nach Kategorie einkaufen',
    'categories.subtitle': 'Finden Sie genau das, was Sie suchen',
    'categories.productsCount': 'Produkte',
    
    // Brands
    'brands.title': 'Marken',
    'brands.shopBy': 'Nach Marke einkaufen',
    'brands.subtitle': 'Produkte von Top-Marken erkunden',
    'brands.viewAll': 'Alle Marken ansehen',
    
    // Cart
    'cart.title': 'Warenkorb',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.continueShopping': 'Weiter einkaufen',
    'cart.subtotal': 'Zwischensumme',
    'cart.tax': 'MwSt.',
    'cart.shipping': 'Versand',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Zur Kasse',
    'cart.remove': 'Entfernen',
    'cart.quantity': 'Menge',
    
    // Checkout
    'checkout.title': 'Kasse',
    'checkout.shipping': 'Versandinformationen',
    'checkout.billing': 'Rechnungsinformationen',
    'checkout.payment': 'Zahlungsmethode',
    'checkout.review': 'Bestellung überprüfen',
    'checkout.sameAsBilling': 'Wie Rechnungsadresse',
    'checkout.placeOrder': 'Bestellung aufgeben',
    'checkout.orderNotes': 'Bestellnotizen',
    'checkout.firstName': 'Vorname',
    'checkout.lastName': 'Nachname',
    'checkout.email': 'E-Mail',
    'checkout.phone': 'Telefon',
    'checkout.company': 'Firma (Optional)',
    'checkout.address': 'Adresse',
    'checkout.addressLine2': 'Wohnung, Suite, etc.',
    'checkout.city': 'Stadt',
    'checkout.state': 'Bundesland',
    'checkout.postalCode': 'Postleitzahl',
    'checkout.country': 'Land',
    'checkout.creditCard': 'Kreditkarte',
    'checkout.paypal': 'PayPal',
    'checkout.bankTransfer': 'Banküberweisung',
    'checkout.orderSummary': 'Bestellübersicht',
    'checkout.contactInformation': 'Kontaktinformationen',
    'checkout.addressLine1': 'Adresszeile 1',
    'checkout.addressLine2Optional': 'Adresszeile 2 (Optional)',
    'checkout.taxVat': 'MwSt. (USt.)',
    'checkout.phoneOptional': 'Telefon (Optional)',
    'checkout.stateOptional': 'Bundesland (Optional)',
    'checkout.billingAddress': 'Rechnungsadresse',
    'checkout.shippingAddress': 'Lieferadresse',
    'checkout.sameAsShipping': 'Wie Lieferadresse',
    
    // Orders
    'orders.title': 'Meine Bestellungen',
    'orders.track': 'Bestellung verfolgen',
    'orders.orderNumber': 'Bestellnummer',
    'orders.date': 'Datum',
    'orders.status': 'Status',
    'orders.total': 'Gesamt',
    'orders.details': 'Details ansehen',
    'orders.trackPlaceholder': 'Geben Sie Ihre Bestellnummer ein',
    'orders.emailPlaceholder': 'Geben Sie Ihre E-Mail ein',
    'orders.trackButton': 'Bestellung verfolgen',
    'orders.noOrders': 'Keine Bestellungen gefunden',
    'orders.search': 'Bestellungen suchen...',
    'orders.allStatus': 'Alle Status',
    'orders.placedOn': 'Bestellt am',
    'orders.items': 'Artikel',
    'orders.startShopping': 'Einkaufen beginnen',
    'orders.tryAdjusting': 'Versuchen Sie, Ihre Suche oder Filter anzupassen',
    'orders.noOrdersYet': 'Sie haben noch keine Bestellungen aufgegeben',
    
    // Order Status
    'status.pending': 'Ausstehend',
    'status.processing': 'In Bearbeitung',
    'status.shipped': 'Versendet',
    'status.delivered': 'Zugestellt',
    'status.cancelled': 'Storniert',
    
    // Payment Status
    'payment.pending': 'Zahlung ausstehend',
    'payment.paid': 'Bezahlt',
    'payment.failed': 'Zahlung fehlgeschlagen',
    'payment.refunded': 'Erstattet',
    
    // Account
    'account.title': 'Mein Konto',
    'account.profile': 'Profil',
    'account.settings': 'Einstellungen',
    'account.profileInformation': 'Profilinformationen',
    'account.editProfile': 'Profil bearbeiten',
    'account.saveChanges': 'Änderungen speichern',
    'account.cancel': 'Abbrechen',
    'account.verifiedAccount': 'Verifiziertes Konto',
    'account.firstName': 'Vorname',
    'account.lastName': 'Nachname',
    'account.email': 'E-Mail-Adresse',
    'account.phone': 'Telefonnummer',
    'account.notProvided': 'Nicht angegeben',
    'account.myOrders': 'Meine Bestellungen',
    'account.trackOrders': 'Bestellungen verfolgen und verwalten',
    'account.addresses': 'Adressen',
    'account.manageAddresses': 'Lieferadressen verwalten',
    'account.accountSettings': 'Kontoeinstellungen',
    'account.preferences': 'Kontoeinstellungen und Sicherheit',
    'account.signOut': 'Abmelden',
    'account.logoutDescription': 'Von Ihrem Konto abmelden',
    'account.viewOrders': 'Ihre Bestellungen ansehen',
    'account.signInToView': 'Melden Sie sich an, um Ihren Bestellverlauf und Sendungsverfolgung zu sehen',
    'account.signInToAccount': 'Bei Ihrem Konto anmelden',
    'account.accessAccount': 'Zugriff auf Ihre Bestellungen, Wunschliste und Kontoeinstellungen',
    'account.createAccount': 'Konto erstellen',
    'account.signInRequired': 'Anmeldung erforderlich',
    
    // Addresses
    'addresses.title': 'Meine Adressen',
    'addresses.subtitle': 'Verwalten Sie Ihre Lieferadressen',
    'addresses.addNew': 'Adresse hinzufügen',
    'addresses.edit': 'Adresse bearbeiten',
    'addresses.name': 'Adressname',
    'addresses.namePlaceholder': 'z.B. Zuhause, Büro',
    'addresses.street': 'Straße',
    'addresses.streetPlaceholder': 'Straße eingeben',
    'addresses.city': 'Stadt',
    'addresses.cityPlaceholder': 'Stadt eingeben',
    'addresses.postalCode': 'Postleitzahl',
    'addresses.postalCodePlaceholder': 'PLZ eingeben',
    'addresses.country': 'Land',
    'addresses.countryPlaceholder': 'Land eingeben',
    'addresses.selectCountry': 'Land auswählen',
    'addresses.state': 'Bundesland/Region',
    'addresses.selectState': 'Bundesland/Region auswählen',
    'addresses.selectCity': 'Stadt auswählen',
    'addresses.default': 'Standard',
    'addresses.setDefault': 'Als Standard festlegen',
    'addresses.noAddresses': 'Keine Adressen gespeichert',
    'addresses.noAddressesDesc': 'Fügen Sie Ihre erste Lieferadresse hinzu.',
    'addresses.addFirst': 'Erste Adresse hinzufügen',
    'addresses.updated': 'Adresse aktualisiert',
    'addresses.updatedDesc': 'Ihre Adresse wurde erfolgreich aktualisiert.',
    'addresses.added': 'Adresse hinzugefügt',
    'addresses.addedDesc': 'Ihre neue Adresse wurde gespeichert.',
    'addresses.deleted': 'Adresse gelöscht',
    'addresses.deletedDesc': 'Ihre Adresse wurde entfernt.',
    'addresses.defaultSet': 'Standardadresse festgelegt',
    'addresses.defaultSetDesc': 'Diese Adresse wird als Standard verwendet.',
    'addresses.deleteConfirm': 'Diese Adresse löschen?',
    'addresses.deleteConfirmDesc': 'Diese Aktion kann nicht rückgängig gemacht werden.',
    
    // Settings
    'settings.title': 'Kontoeinstellungen',
    'settings.subtitle': 'Verwalten Sie Ihre Kontoeinstellungen',
    'settings.changePassword': 'Passwort ändern',
    'settings.changePasswordDesc': 'Aktualisieren Sie Ihr Passwort.',
    'settings.currentPassword': 'Aktuelles Passwort',
    'settings.newPassword': 'Neues Passwort',
    'settings.confirmPassword': 'Neues Passwort bestätigen',
    'settings.updatePassword': 'Passwort aktualisieren',
    'settings.passwordChanged': 'Passwort geändert',
    'settings.passwordChangedDesc': 'Ihr Passwort wurde erfolgreich aktualisiert.',
    'settings.passwordMismatch': 'Passwörter stimmen nicht überein',
    'settings.passwordMismatchDesc': 'Bitte stellen Sie sicher, dass Ihre Passwörter übereinstimmen.',
    'settings.passwordTooShort': 'Passwort zu kurz',
    'settings.passwordTooShortDesc': 'Das Passwort muss mindestens 8 Zeichen lang sein.',
    'settings.notifications': 'Benachrichtigungen',
    'settings.notificationsDesc': 'Wählen Sie, welche Benachrichtigungen Sie erhalten.',
    'settings.orderUpdates': 'Bestellstatus',
    'settings.orderUpdatesDesc': 'Benachrichtigungen über Ihren Bestellstatus erhalten.',
    'settings.promotions': 'Werbeaktionen',
    'settings.promotionsDesc': 'Angebote und Rabatte erhalten.',
    'settings.newsletter': 'Newsletter',
    'settings.newsletterDesc': 'Bleiben Sie über unsere neuesten Nachrichten informiert.',
    'settings.language': 'Sprache',
    'settings.languageDesc': 'Wählen Sie Ihre bevorzugte Sprache.',
    'settings.dangerZone': 'Gefahrenzone',
    'settings.dangerZoneDesc': 'Unwiderrufliche Aktionen für Ihr Konto.',
    'settings.deleteAccount': 'Konto löschen',
    'settings.deleteConfirm': 'Sind Sie sicher?',
    'settings.deleteConfirmDesc': 'Dies löscht Ihr Konto und alle zugehörigen Daten dauerhaft.',
    'settings.accountDeleted': 'Konto gelöscht',
    'settings.accountDeletedDesc': 'Ihr Konto wurde dauerhaft gelöscht.',
    
    // Auth
    'auth.login': 'Anmelden',
    'auth.register': 'Konto erstellen',
    'auth.createAccount': 'Konto erstellen',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'auth.welcomeBack': 'Willkommen zurück',
    'auth.loginSubtitle': 'Melden Sie sich in Ihrem Konto an, um weiter einzukaufen',
    'auth.registerSubtitle': 'Treten Sie TeleTrade Hub bei und beginnen Sie mit dem Einkaufen',
    'auth.loginSuccess': 'Anmeldung erfolgreich!',
    'auth.loginFailed': 'Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'auth.registerSuccess': 'Konto erfolgreich erstellt!',
    'auth.registerFailed': 'Registrierung fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'auth.emailPlaceholder': 'ihre@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.fullName': 'Vollständiger Name',
    'auth.fullNamePlaceholder': 'Max Mustermann',
    'auth.phone': 'Telefon',
    'auth.phonePlaceholder': '+49 30 123 456 789',
    'auth.rememberMe': 'Angemeldet bleiben',
    'auth.passwordRequirements': 'Passwortanforderungen:',
    'auth.passwordMinLength': 'Mindestens 8 Zeichen',
    'auth.passwordUppercase': 'Ein Großbuchstabe',
    'auth.passwordLowercase': 'Ein Kleinbuchstabe',
    'auth.passwordNumber': 'Eine Zahl',
    'auth.passwordSpecial': 'Ein Sonderzeichen',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Ein Fehler ist aufgetreten',
    'common.retry': 'Wiederholen',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Ansehen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.search': 'Suchen',
    'common.close': 'Schließen',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.viewAll': 'Alle ansehen',
    'common.optional': '(Optional)',
    
    // Home
    'home.productsAvailable': 'Verfügbare Produkte',
    'home.topBrands': 'Top-Marken',
    'home.customerSupport': 'Kundensupport',
    'home.securePayments': 'Sichere Zahlungen',
    'home.ctaTitle': 'Bereit, Ihre Technik zu verbessern?',
    'home.ctaSubtitle': 'Durchsuchen Sie unsere umfangreiche Sammlung von Premium-Telekommunikationsprodukten von führenden Marken weltweit.',
    'home.startShopping': 'Einkaufen beginnen',
    
    // Footer
    'footer.about': 'Über uns',
    'footer.contact': 'Kontakt',
    'footer.howToBuy': 'Kaufanleitung',
    'footer.shipping': 'Versandrichtlinien',
    'footer.returns': 'Rückgaberecht',
    'footer.terms': 'AGB',
    'footer.privacy': 'Datenschutz',
    'footer.copyright': '© 2026 TeleTrade Hub. Alle Rechte vorbehalten.',
    'footer.description': 'Ihr vertrauenswürdiger Partner für Premium-Telekommunikationsprodukte. Qualitätsgeräte von Top-Marken weltweit.',
    'footer.company': 'Unternehmen',
    'footer.policies': 'Richtlinien',
    'footer.secureCheckout': 'Sicherer Checkout',
    'footer.safePayment': 'Sichere Zahlung',
    'footer.fastDelivery': 'Schnelle Lieferung',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.categories': 'Catégories',
    'nav.brands': 'Marques',
    'nav.cart': 'Panier',
    'nav.account': 'Compte',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    'nav.logout': 'Déconnexion',
    'nav.myOrders': 'Mes Commandes',
    'nav.trackOrder': 'Suivre la Commande',
    'nav.signIn': 'Se connecter',
    
    // Hero
    'hero.title': 'Produits Télécom Premium',
    'hero.subtitle': 'Découvrez les derniers smartphones, tablettes et accessoires des meilleures marques',
    'hero.cta': 'Acheter Maintenant',
    'hero.secondary': 'Voir les Catégories',
    'hero.newArrivals': 'Nouveautés Disponibles',
    'hero.freeShipping': 'Livraison Gratuite',
    'hero.warranty': 'Garantie 2 Ans',
    'hero.securePayment': 'Paiement Sécurisé',
    'hero.support': 'Support 24/7',
    
    // Products
    'products.title': 'Produits',
    'products.featured': 'Produits Vedettes',
    'products.featuredSubtitle': 'Nos meilleurs choix',
    'products.viewAll': 'Voir Tous les Produits',
    'products.all': 'Tous les Produits',
    'products.search': 'Rechercher des produits...',
    'products.filter': 'Filtrer',
    'products.sort': 'Trier par',
    'products.sortPrice': 'Prix',
    'products.sortName': 'Nom',
    'products.sortNewest': 'Plus récent',
    'products.asc': 'Du plus bas au plus haut',
    'products.desc': 'Du plus haut au plus bas',
    'products.inStock': 'En Stock',
    'products.outOfStock': 'Rupture de Stock',
    'products.lowStock': 'Stock Faible',
    'products.addToCart': 'Ajouter au Panier',
    'products.viewDetails': 'Voir les Détails',
    'products.quickView': 'Aperçu Rapide',
    'products.noProducts': 'Aucun produit trouvé',
    'products.clearFilters': 'Effacer les Filtres',
    'products.priceRange': 'Gamme de Prix',
    'products.color': 'Couleur',
    'products.storage': 'Stockage',
    'products.ram': 'RAM',
    'products.category': 'Catégorie',
    'products.brand': 'Marque',
    'products.specifications': 'Spécifications',
    'products.description': 'Description',
    'products.relatedProducts': 'Produits Similaires',
    'products.sku': 'SKU',
    'products.warranty': 'Garantie',
    'products.months': 'mois',
    'products.month': 'Mois',
    'products.loginToViewPrice': 'Connectez-vous pour voir le prix',
    'products.fastDelivery': 'Livraison Rapide',
    'products.securePayment': 'Paiement Sécurisé',
    'products.easyReturns': 'Retours Faciles',
    'products.signInForPricing': 'Connectez-vous pour voir les prix exclusifs et les offres',
    'products.loginToBuy': 'Se connecter pour Acheter',
    
    // Categories
    'categories.title': 'Catégories',
    'categories.shopBy': 'Acheter par Catégorie',
    'categories.subtitle': 'Trouvez exactement ce que vous cherchez',
    'categories.productsCount': 'produits',
    
    // Brands
    'brands.title': 'Marques',
    'brands.shopBy': 'Acheter par Marque',
    'brands.subtitle': 'Explorez les produits des meilleures marques',
    'brands.viewAll': 'Voir Toutes les Marques',
    
    // Cart
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.continueShopping': 'Continuer les Achats',
    'cart.subtotal': 'Sous-total',
    'cart.tax': 'Taxe',
    'cart.shipping': 'Livraison',
    'cart.total': 'Total',
    'cart.checkout': 'Passer à la Caisse',
    'cart.remove': 'Retirer',
    'cart.quantity': 'Quantité',
    
    // Checkout
    'checkout.title': 'Commande',
    'checkout.shipping': 'Informations de Livraison',
    'checkout.billing': 'Informations de Facturation',
    'checkout.payment': 'Méthode de Paiement',
    'checkout.review': 'Réviser la Commande',
    'checkout.sameAsBilling': 'Identique à l\'adresse de facturation',
    'checkout.placeOrder': 'Passer la Commande',
    'checkout.orderNotes': 'Notes de Commande',
    'checkout.firstName': 'Prénom',
    'checkout.lastName': 'Nom',
    'checkout.email': 'Email',
    'checkout.phone': 'Téléphone',
    'checkout.company': 'Entreprise (Optionnel)',
    'checkout.address': 'Adresse',
    'checkout.addressLine2': 'Appartement, suite, etc.',
    'checkout.city': 'Ville',
    'checkout.state': 'État/Province',
    'checkout.postalCode': 'Code Postal',
    'checkout.country': 'Pays',
    'checkout.creditCard': 'Carte de Crédit',
    'checkout.paypal': 'PayPal',
    'checkout.bankTransfer': 'Virement Bancaire',
    'checkout.orderSummary': 'Résumé de la Commande',
    'checkout.contactInformation': 'Informations de Contact',
    'checkout.addressLine1': 'Ligne d\'Adresse 1',
    'checkout.addressLine2Optional': 'Ligne d\'Adresse 2 (Optionnel)',
    'checkout.taxVat': 'TVA',
    'checkout.phoneOptional': 'Téléphone (Optionnel)',
    'checkout.stateOptional': 'État/Province (Optionnel)',
    'checkout.billingAddress': 'Adresse de Facturation',
    'checkout.shippingAddress': 'Adresse de Livraison',
    'checkout.sameAsShipping': 'Identique à l\'adresse de livraison',
    
    // Orders
    'orders.title': 'Mes Commandes',
    'orders.track': 'Suivre la Commande',
    'orders.orderNumber': 'Numéro de Commande',
    'orders.date': 'Date',
    'orders.status': 'Statut',
    'orders.total': 'Total',
    'orders.details': 'Voir les Détails',
    'orders.trackPlaceholder': 'Entrez votre numéro de commande',
    'orders.emailPlaceholder': 'Entrez votre email',
    'orders.trackButton': 'Suivre la Commande',
    'orders.noOrders': 'Aucune commande trouvée',
    'orders.search': 'Rechercher des commandes...',
    'orders.allStatus': 'Tous les Statuts',
    'orders.placedOn': 'Passée le',
    'orders.items': 'article(s)',
    'orders.startShopping': 'Commencer à Acheter',
    'orders.tryAdjusting': 'Essayez d\'ajuster votre recherche ou vos filtres',
    'orders.noOrdersYet': 'Vous n\'avez pas encore passé de commande',
    
    // Order Status
    'status.pending': 'En Attente',
    'status.processing': 'En Traitement',
    'status.shipped': 'Expédié',
    'status.delivered': 'Livré',
    'status.cancelled': 'Annulé',
    
    // Payment Status
    'payment.pending': 'Paiement en Attente',
    'payment.paid': 'Payé',
    'payment.failed': 'Paiement Échoué',
    'payment.refunded': 'Remboursé',
    
    // Account
    'account.title': 'Mon Compte',
    'account.profile': 'Profil',
    'account.settings': 'Paramètres',
    'account.profileInformation': 'Informations du Profil',
    'account.editProfile': 'Modifier le Profil',
    'account.saveChanges': 'Enregistrer les Modifications',
    'account.cancel': 'Annuler',
    'account.verifiedAccount': 'Compte Vérifié',
    'account.firstName': 'Prénom',
    'account.lastName': 'Nom',
    'account.email': 'Adresse Email',
    'account.phone': 'Numéro de Téléphone',
    'account.notProvided': 'Non fourni',
    'account.myOrders': 'Mes Commandes',
    'account.trackOrders': 'Suivre et gérer vos commandes',
    'account.addresses': 'Adresses',
    'account.manageAddresses': 'Gérer les adresses de livraison',
    'account.accountSettings': 'Paramètres du Compte',
    'account.preferences': 'Préférences et sécurité du compte',
    'account.signOut': 'Se Déconnecter',
    'account.logoutDescription': 'Déconnectez-vous de votre compte',
    'account.viewOrders': 'Voir vos commandes',
    'account.signInToView': 'Connectez-vous pour voir votre historique de commandes et suivre les expéditions',
    'account.signInToAccount': 'Connectez-vous à votre compte',
    'account.accessAccount': 'Accédez à vos commandes, liste de souhaits et paramètres du compte',
    'account.createAccount': 'Créer un Compte',
    'account.signInRequired': 'Connexion requise',
    
    // Addresses
    'addresses.title': 'Mes Adresses',
    'addresses.subtitle': 'Gérer vos adresses de livraison',
    'addresses.addNew': 'Ajouter une Adresse',
    'addresses.edit': 'Modifier l\'Adresse',
    'addresses.name': 'Nom de l\'Adresse',
    'addresses.namePlaceholder': 'ex: Domicile, Bureau',
    'addresses.street': 'Adresse',
    'addresses.streetPlaceholder': 'Entrez l\'adresse',
    'addresses.city': 'Ville',
    'addresses.cityPlaceholder': 'Entrez la ville',
    'addresses.postalCode': 'Code Postal',
    'addresses.postalCodePlaceholder': 'Entrez le code postal',
    'addresses.country': 'Pays',
    'addresses.countryPlaceholder': 'Entrez le pays',
    'addresses.selectCountry': 'Sélectionner le pays',
    'addresses.state': 'État/Région',
    'addresses.selectState': 'Sélectionner l\'état/région',
    'addresses.selectCity': 'Sélectionner la ville',
    'addresses.default': 'Par Défaut',
    'addresses.setDefault': 'Définir par défaut',
    'addresses.noAddresses': 'Aucune adresse enregistrée',
    'addresses.noAddressesDesc': 'Ajoutez votre première adresse de livraison pour accélérer le paiement.',
    'addresses.addFirst': 'Ajouter votre première adresse',
    'addresses.updated': 'Adresse mise à jour',
    'addresses.updatedDesc': 'Votre adresse a été mise à jour avec succès.',
    'addresses.added': 'Adresse ajoutée',
    'addresses.addedDesc': 'Votre nouvelle adresse a été enregistrée.',
    'addresses.deleted': 'Adresse supprimée',
    'addresses.deletedDesc': 'Votre adresse a été supprimée.',
    'addresses.defaultSet': 'Adresse par défaut définie',
    'addresses.defaultSetDesc': 'Cette adresse sera utilisée comme adresse de livraison par défaut.',
    'addresses.deleteConfirm': 'Supprimer cette adresse?',
    'addresses.deleteConfirmDesc': 'Cette action ne peut pas être annulée.',
    
    // Settings
    'settings.title': 'Paramètres du Compte',
    'settings.subtitle': 'Gérer les préférences de votre compte',
    'settings.changePassword': 'Changer le Mot de Passe',
    'settings.changePasswordDesc': 'Mettez à jour votre mot de passe pour sécuriser votre compte.',
    'settings.currentPassword': 'Mot de Passe Actuel',
    'settings.newPassword': 'Nouveau Mot de Passe',
    'settings.confirmPassword': 'Confirmer le Nouveau Mot de Passe',
    'settings.updatePassword': 'Mettre à Jour le Mot de Passe',
    'settings.passwordChanged': 'Mot de passe modifié',
    'settings.passwordChangedDesc': 'Votre mot de passe a été mis à jour avec succès.',
    'settings.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'settings.passwordMismatchDesc': 'Veuillez vous assurer que vos mots de passe correspondent.',
    'settings.passwordTooShort': 'Mot de passe trop court',
    'settings.passwordTooShortDesc': 'Le mot de passe doit contenir au moins 8 caractères.',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Choisissez les notifications que vous recevez.',
    'settings.orderUpdates': 'Mises à Jour des Commandes',
    'settings.orderUpdatesDesc': 'Soyez informé de l\'état de vos commandes.',
    'settings.promotions': 'Promotions',
    'settings.promotionsDesc': 'Recevez des offres promotionnelles et des réductions.',
    'settings.newsletter': 'Newsletter',
    'settings.newsletterDesc': 'Restez informé de nos dernières actualités.',
    'settings.language': 'Langue',
    'settings.languageDesc': 'Choisissez votre langue préférée.',
    'settings.dangerZone': 'Zone Dangereuse',
    'settings.dangerZoneDesc': 'Actions irréversibles pour votre compte.',
    'settings.deleteAccount': 'Supprimer le Compte',
    'settings.deleteConfirm': 'Êtes-vous sûr?',
    'settings.deleteConfirmDesc': 'Cela supprimera définitivement votre compte et toutes les données associées. Cette action ne peut pas être annulée.',
    'settings.accountDeleted': 'Compte supprimé',
    'settings.accountDeletedDesc': 'Votre compte a été définitivement supprimé.',
    
    // Auth
    'auth.login': 'Connexion',
    'auth.register': 'Créer un Compte',
    'auth.createAccount': 'Créer un Compte',
    'auth.email': 'Email',
    'auth.password': 'Mot de Passe',
    'auth.confirmPassword': 'Confirmer le Mot de Passe',
    'auth.forgotPassword': 'Mot de Passe Oublié?',
    'auth.noAccount': 'Vous n\'avez pas de compte?',
    'auth.hasAccount': 'Vous avez déjà un compte?',
    'auth.welcomeBack': 'Bon Retour',
    'auth.loginSubtitle': 'Connectez-vous à votre compte pour continuer vos achats',
    'auth.registerSubtitle': 'Rejoignez TeleTrade Hub et commencez à acheter',
    'auth.loginSuccess': 'Connexion réussie!',
    'auth.loginFailed': 'Échec de la connexion. Veuillez réessayer.',
    'auth.registerSuccess': 'Compte créé avec succès!',
    'auth.registerFailed': 'Échec de l\'inscription. Veuillez réessayer.',
    'auth.emailPlaceholder': 'votre@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.fullName': 'Nom Complet',
    'auth.fullNamePlaceholder': 'Jean Dupont',
    'auth.phone': 'Téléphone',
    'auth.phonePlaceholder': '+33 1 23 45 67 89',
    'auth.rememberMe': 'Se souvenir de moi',
    'auth.passwordRequirements': 'Exigences du mot de passe:',
    'auth.passwordMinLength': 'Au moins 8 caractères',
    'auth.passwordUppercase': 'Une lettre majuscule',
    'auth.passwordLowercase': 'Une lettre minuscule',
    'auth.passwordNumber': 'Un chiffre',
    'auth.passwordSpecial': 'Un caractère spécial',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur s\'est produite',
    'common.retry': 'Réessayer',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.search': 'Rechercher',
    'common.close': 'Fermer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.viewAll': 'Voir Tout',
    'common.optional': '(Optionnel)',
    
    // Home
    'home.productsAvailable': 'Produits Disponibles',
    'home.topBrands': 'Meilleures Marques',
    'home.customerSupport': 'Support Client',
    'home.securePayments': 'Paiements Sécurisés',
    'home.ctaTitle': 'Prêt à améliorer votre technologie?',
    'home.ctaSubtitle': 'Parcourez notre vaste collection de produits de télécommunication premium des meilleures marques mondiales.',
    'home.startShopping': 'Commencer à Acheter',
    
    // Footer
    'footer.about': 'À Propos',
    'footer.contact': 'Contact',
    'footer.howToBuy': 'Comment Acheter',
    'footer.shipping': 'Politique de Livraison',
    'footer.returns': 'Politique de Retour',
    'footer.terms': 'Conditions Générales',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.copyright': '© 2026 TeleTrade Hub. Tous droits réservés.',
    'footer.description': 'Votre partenaire de confiance pour les produits de télécommunication premium. Appareils de qualité des meilleures marques mondiales.',
    'footer.company': 'Entreprise',
    'footer.policies': 'Politiques',
    'footer.secureCheckout': 'Paiement Sécurisé',
    'footer.safePayment': 'Paiement Sécurisé',
    'footer.fastDelivery': 'Livraison Rapide',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.products': 'Productos',
    'nav.categories': 'Categorías',
    'nav.brands': 'Marcas',
    'nav.cart': 'Carrito',
    'nav.account': 'Cuenta',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar Sesión',
    'nav.myOrders': 'Mis Pedidos',
    'nav.trackOrder': 'Rastrear Pedido',
    'nav.signIn': 'Iniciar Sesión',
    
    // Hero
    'hero.title': 'Productos de Telecomunicaciones Premium',
    'hero.subtitle': 'Descubre los últimos smartphones, tablets y accesorios de las mejores marcas',
    'hero.cta': 'Comprar Ahora',
    'hero.secondary': 'Ver Categorías',
    'hero.newArrivals': 'Nuevos Llegados Disponibles',
    'hero.freeShipping': 'Envío Gratis',
    'hero.warranty': 'Garantía de 2 Años',
    'hero.securePayment': 'Pago Seguro',
    'hero.support': 'Soporte 24/7',
    
    // Products
    'products.title': 'Productos',
    'products.featured': 'Productos Destacados',
    'products.featuredSubtitle': 'Nuestras mejores selecciones',
    'products.viewAll': 'Ver Todos los Productos',
    'products.all': 'Todos los Productos',
    'products.search': 'Buscar productos...',
    'products.filter': 'Filtrar',
    'products.sort': 'Ordenar por',
    'products.sortPrice': 'Precio',
    'products.sortName': 'Nombre',
    'products.sortNewest': 'Más Recientes',
    'products.asc': 'De Menor a Mayor',
    'products.desc': 'De Mayor a Menor',
    'products.inStock': 'En Stock',
    'products.outOfStock': 'Agotado',
    'products.lowStock': 'Stock Bajo',
    'products.addToCart': 'Añadir al Carrito',
    'products.viewDetails': 'Ver Detalles',
    'products.quickView': 'Vista Rápida',
    'products.noProducts': 'No se encontraron productos',
    'products.clearFilters': 'Limpiar Filtros',
    'products.priceRange': 'Rango de Precios',
    'products.color': 'Color',
    'products.storage': 'Almacenamiento',
    'products.ram': 'RAM',
    'products.category': 'Categoría',
    'products.brand': 'Marca',
    'products.specifications': 'Especificaciones',
    'products.description': 'Descripción',
    'products.relatedProducts': 'Productos Relacionados',
    'products.sku': 'SKU',
    'products.warranty': 'Garantía',
    'products.months': 'meses',
    'products.month': 'Mes',
    'products.loginToViewPrice': 'Inicia sesión para ver el precio',
    'products.fastDelivery': 'Entrega Rápida',
    'products.securePayment': 'Pago Seguro',
    'products.easyReturns': 'Devoluciones Fáciles',
    'products.signInForPricing': 'Inicia sesión para ver precios exclusivos y ofertas',
    'products.loginToBuy': 'Iniciar Sesión para Comprar',
    
    // Categories
    'categories.title': 'Categorías',
    'categories.shopBy': 'Comprar por Categoría',
    'categories.subtitle': 'Encuentra exactamente lo que buscas',
    'categories.productsCount': 'productos',
    
    // Brands
    'brands.title': 'Marcas',
    'brands.shopBy': 'Comprar por Marca',
    'brands.subtitle': 'Explora productos de las mejores marcas',
    'brands.viewAll': 'Ver Todas las Marcas',
    
    // Cart
    'cart.title': 'Carrito de Compras',
    'cart.empty': 'Tu carrito está vacío',
    'cart.continueShopping': 'Continuar Comprando',
    'cart.subtotal': 'Subtotal',
    'cart.tax': 'Impuesto',
    'cart.shipping': 'Envío',
    'cart.total': 'Total',
    'cart.checkout': 'Proceder al Pago',
    'cart.remove': 'Eliminar',
    'cart.quantity': 'Cantidad',
    
    // Checkout
    'checkout.title': 'Pago',
    'checkout.shipping': 'Información de Envío',
    'checkout.billing': 'Información de Facturación',
    'checkout.payment': 'Método de Pago',
    'checkout.review': 'Revisar Pedido',
    'checkout.sameAsBilling': 'Igual que la dirección de facturación',
    'checkout.placeOrder': 'Realizar Pedido',
    'checkout.orderNotes': 'Notas del Pedido',
    'checkout.firstName': 'Nombre',
    'checkout.lastName': 'Apellido',
    'checkout.email': 'Email',
    'checkout.phone': 'Teléfono',
    'checkout.company': 'Empresa (Opcional)',
    'checkout.address': 'Dirección',
    'checkout.addressLine2': 'Apartamento, suite, etc.',
    'checkout.city': 'Ciudad',
    'checkout.state': 'Estado/Provincia',
    'checkout.postalCode': 'Código Postal',
    'checkout.country': 'País',
    'checkout.creditCard': 'Tarjeta de Crédito',
    'checkout.paypal': 'PayPal',
    'checkout.bankTransfer': 'Transferencia Bancaria',
    'checkout.orderSummary': 'Resumen del Pedido',
    'checkout.contactInformation': 'Información de Contacto',
    'checkout.addressLine1': 'Línea de Dirección 1',
    'checkout.addressLine2Optional': 'Línea de Dirección 2 (Opcional)',
    'checkout.taxVat': 'Impuesto (IVA)',
    'checkout.phoneOptional': 'Teléfono (Opcional)',
    'checkout.stateOptional': 'Estado/Provincia (Opcional)',
    'checkout.billingAddress': 'Dirección de Facturación',
    'checkout.shippingAddress': 'Dirección de Envío',
    'checkout.sameAsShipping': 'Igual que la dirección de envío',
    
    // Orders
    'orders.title': 'Mis Pedidos',
    'orders.track': 'Rastrear Pedido',
    'orders.orderNumber': 'Número de Pedido',
    'orders.date': 'Fecha',
    'orders.status': 'Estado',
    'orders.total': 'Total',
    'orders.details': 'Ver Detalles',
    'orders.trackPlaceholder': 'Ingresa tu número de pedido',
    'orders.emailPlaceholder': 'Ingresa tu email',
    'orders.trackButton': 'Rastrear Pedido',
    'orders.noOrders': 'No se encontraron pedidos',
    'orders.search': 'Buscar pedidos...',
    'orders.allStatus': 'Todos los Estados',
    'orders.placedOn': 'Realizado el',
    'orders.items': 'artículo(s)',
    'orders.startShopping': 'Comenzar a Comprar',
    'orders.tryAdjusting': 'Intenta ajustar tu búsqueda o filtros',
    'orders.noOrdersYet': 'Aún no has realizado ningún pedido',
    
    // Order Status
    'status.pending': 'Pendiente',
    'status.processing': 'Procesando',
    'status.shipped': 'Enviado',
    'status.delivered': 'Entregado',
    'status.cancelled': 'Cancelado',
    
    // Payment Status
    'payment.pending': 'Pago Pendiente',
    'payment.paid': 'Pagado',
    'payment.failed': 'Pago Fallido',
    'payment.refunded': 'Reembolsado',
    
    // Account
    'account.title': 'Mi Cuenta',
    'account.profile': 'Perfil',
    'account.settings': 'Configuración',
    'account.profileInformation': 'Información del Perfil',
    'account.editProfile': 'Editar Perfil',
    'account.saveChanges': 'Guardar Cambios',
    'account.cancel': 'Cancelar',
    'account.verifiedAccount': 'Cuenta Verificada',
    'account.firstName': 'Nombre',
    'account.lastName': 'Apellido',
    'account.email': 'Dirección de Email',
    'account.phone': 'Número de Teléfono',
    'account.notProvided': 'No proporcionado',
    'account.myOrders': 'Mis Pedidos',
    'account.trackOrders': 'Rastrear y gestionar tus pedidos',
    'account.addresses': 'Direcciones',
    'account.manageAddresses': 'Gestionar direcciones de entrega',
    'account.accountSettings': 'Configuración de la Cuenta',
    'account.preferences': 'Preferencias y seguridad de la cuenta',
    'account.signOut': 'Cerrar Sesión',
    'account.logoutDescription': 'Cerrar sesión de tu cuenta',
    'account.viewOrders': 'Ver tus pedidos',
    'account.signInToView': 'Inicia sesión para ver tu historial de pedidos y rastrear envíos',
    'account.signInToAccount': 'Inicia sesión en tu cuenta',
    'account.accessAccount': 'Accede a tus pedidos, lista de deseos y configuración de cuenta',
    'account.createAccount': 'Crear Cuenta',
    'account.signInRequired': 'Inicio de sesión requerido',
    
    // Addresses
    'addresses.title': 'Mis Direcciones',
    'addresses.subtitle': 'Gestiona tus direcciones de entrega',
    'addresses.addNew': 'Añadir Dirección',
    'addresses.edit': 'Editar Dirección',
    'addresses.name': 'Nombre de la Dirección',
    'addresses.namePlaceholder': 'ej: Casa, Oficina',
    'addresses.street': 'Dirección',
    'addresses.streetPlaceholder': 'Ingresa la dirección',
    'addresses.city': 'Ciudad',
    'addresses.cityPlaceholder': 'Ingresa la ciudad',
    'addresses.postalCode': 'Código Postal',
    'addresses.postalCodePlaceholder': 'Ingresa el código postal',
    'addresses.country': 'País',
    'addresses.countryPlaceholder': 'Ingresa el país',
    'addresses.selectCountry': 'Seleccionar país',
    'addresses.state': 'Estado/Región',
    'addresses.selectState': 'Seleccionar estado/región',
    'addresses.selectCity': 'Seleccionar ciudad',
    'addresses.default': 'Por Defecto',
    'addresses.setDefault': 'Establecer como predeterminada',
    'addresses.noAddresses': 'No hay direcciones guardadas',
    'addresses.noAddressesDesc': 'Añade tu primera dirección de entrega para agilizar el pago.',
    'addresses.addFirst': 'Añade tu primera dirección',
    'addresses.updated': 'Dirección actualizada',
    'addresses.updatedDesc': 'Tu dirección ha sido actualizada exitosamente.',
    'addresses.added': 'Dirección añadida',
    'addresses.addedDesc': 'Tu nueva dirección ha sido guardada.',
    'addresses.deleted': 'Dirección eliminada',
    'addresses.deletedDesc': 'Tu dirección ha sido eliminada.',
    'addresses.defaultSet': 'Dirección predeterminada establecida',
    'addresses.defaultSetDesc': 'Esta dirección se utilizará como tu dirección de entrega predeterminada.',
    'addresses.deleteConfirm': '¿Eliminar esta dirección?',
    'addresses.deleteConfirmDesc': 'Esta acción no se puede deshacer.',
    
    // Settings
    'settings.title': 'Configuración de la Cuenta',
    'settings.subtitle': 'Gestiona las preferencias de tu cuenta',
    'settings.changePassword': 'Cambiar Contraseña',
    'settings.changePasswordDesc': 'Actualiza tu contraseña para mantener tu cuenta segura.',
    'settings.currentPassword': 'Contraseña Actual',
    'settings.newPassword': 'Nueva Contraseña',
    'settings.confirmPassword': 'Confirmar Nueva Contraseña',
    'settings.updatePassword': 'Actualizar Contraseña',
    'settings.passwordChanged': 'Contraseña cambiada',
    'settings.passwordChangedDesc': 'Tu contraseña ha sido actualizada exitosamente.',
    'settings.passwordMismatch': 'Las contraseñas no coinciden',
    'settings.passwordMismatchDesc': 'Por favor asegúrate de que las contraseñas coincidan.',
    'settings.passwordTooShort': 'Contraseña muy corta',
    'settings.passwordTooShortDesc': 'La contraseña debe tener al menos 8 caracteres.',
    'settings.notifications': 'Notificaciones',
    'settings.notificationsDesc': 'Elige qué notificaciones recibes.',
    'settings.orderUpdates': 'Actualizaciones de Pedidos',
    'settings.orderUpdatesDesc': 'Recibe notificaciones sobre el estado de tus pedidos.',
    'settings.promotions': 'Promociones',
    'settings.promotionsDesc': 'Recibe ofertas promocionales y descuentos.',
    'settings.newsletter': 'Boletín',
    'settings.newsletterDesc': 'Mantente actualizado con nuestras últimas noticias.',
    'settings.language': 'Idioma',
    'settings.languageDesc': 'Elige tu idioma preferido.',
    'settings.dangerZone': 'Zona de Peligro',
    'settings.dangerZoneDesc': 'Acciones irreversibles para tu cuenta.',
    'settings.deleteAccount': 'Eliminar Cuenta',
    'settings.deleteConfirm': '¿Estás seguro?',
    'settings.deleteConfirmDesc': 'Esto eliminará permanentemente tu cuenta y todos los datos asociados. Esta acción no se puede deshacer.',
    'settings.accountDeleted': 'Cuenta eliminada',
    'settings.accountDeletedDesc': 'Tu cuenta ha sido eliminada permanentemente.',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Crear Cuenta',
    'auth.createAccount': 'Crear Cuenta',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.forgotPassword': '¿Olvidaste tu Contraseña?',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.hasAccount': '¿Ya tienes una cuenta?',
    'auth.welcomeBack': 'Bienvenido de Nuevo',
    'auth.loginSubtitle': 'Inicia sesión en tu cuenta para continuar comprando',
    'auth.registerSubtitle': 'Únete a TeleTrade Hub y comienza a comprar',
    'auth.loginSuccess': '¡Inicio de sesión exitoso!',
    'auth.loginFailed': 'Error al iniciar sesión. Por favor intenta de nuevo.',
    'auth.registerSuccess': '¡Cuenta creada exitosamente!',
    'auth.registerFailed': 'Error en el registro. Por favor intenta de nuevo.',
    'auth.emailPlaceholder': 'tu@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.fullName': 'Nombre Completo',
    'auth.fullNamePlaceholder': 'Juan Pérez',
    'auth.phone': 'Teléfono',
    'auth.phonePlaceholder': '+34 123 456 789',
    'auth.rememberMe': 'Recordarme',
    'auth.passwordRequirements': 'Requisitos de la contraseña:',
    'auth.passwordMinLength': 'Al menos 8 caracteres',
    'auth.passwordUppercase': 'Una letra mayúscula',
    'auth.passwordLowercase': 'Una letra minúscula',
    'auth.passwordNumber': 'Un número',
    'auth.passwordSpecial': 'Un carácter especial',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error',
    'common.retry': 'Reintentar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.search': 'Buscar',
    'common.close': 'Cerrar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.viewAll': 'Ver Todo',
    'common.optional': '(Opcional)',
    
    // Home
    'home.productsAvailable': 'Productos Disponibles',
    'home.topBrands': 'Mejores Marcas',
    'home.customerSupport': 'Atención al Cliente',
    'home.securePayments': 'Pagos Seguros',
    'home.ctaTitle': '¿Listo para mejorar tu tecnología?',
    'home.ctaSubtitle': 'Explora nuestra amplia colección de productos de telecomunicaciones premium de las mejores marcas del mundo.',
    'home.startShopping': 'Comenzar a Comprar',
    
    // Footer
    'footer.about': 'Acerca de Nosotros',
    'footer.contact': 'Contacto',
    'footer.howToBuy': 'Cómo Comprar',
    'footer.shipping': 'Política de Envío',
    'footer.returns': 'Política de Devoluciones',
    'footer.terms': 'Términos y Condiciones',
    'footer.privacy': 'Política de Privacidad',
    'footer.copyright': '© 2026 TeleTrade Hub. Todos los derechos reservados.',
    'footer.description': 'Tu socio de confianza para productos de telecomunicaciones premium. Dispositivos de calidad de las mejores marcas del mundo.',
    'footer.company': 'Empresa',
    'footer.policies': 'Políticas',
    'footer.secureCheckout': 'Pago Seguro',
    'footer.safePayment': 'Pago Seguro',
    'footer.fastDelivery': 'Entrega Rápida',
  },
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Prodotti',
    'nav.categories': 'Categorie',
    'nav.brands': 'Marchi',
    'nav.cart': 'Carrello',
    'nav.account': 'Account',
    'nav.login': 'Accedi',
    'nav.register': 'Registrati',
    'nav.logout': 'Esci',
    'nav.myOrders': 'I Miei Ordini',
    'nav.trackOrder': 'Traccia Ordine',
    'nav.signIn': 'Accedi',
    
    // Hero
    'hero.title': 'Prodotti Telecom Premium',
    'hero.subtitle': 'Scopri gli ultimi smartphone, tablet e accessori dei migliori marchi',
    'hero.cta': 'Acquista Ora',
    'hero.secondary': 'Visualizza Categorie',
    'hero.newArrivals': 'Nuovi Arrivi Disponibili',
    'hero.freeShipping': 'Spedizione Gratuita',
    'hero.warranty': 'Garanzia 2 Anni',
    'hero.securePayment': 'Pagamento Sicuro',
    'hero.support': 'Supporto 24/7',
    
    // Products
    'products.title': 'Prodotti',
    'products.featured': 'Prodotti in Evidenza',
    'products.featuredSubtitle': 'Le nostre migliori scelte',
    'products.viewAll': 'Visualizza Tutti i Prodotti',
    'products.all': 'Tutti i Prodotti',
    'products.search': 'Cerca prodotti...',
    'products.filter': 'Filtra',
    'products.sort': 'Ordina per',
    'products.sortPrice': 'Prezzo',
    'products.sortName': 'Nome',
    'products.sortNewest': 'Più Recenti',
    'products.asc': 'Dal Basso all\'Alto',
    'products.desc': 'Dall\'Alto al Basso',
    'products.inStock': 'Disponibile',
    'products.outOfStock': 'Esaurito',
    'products.lowStock': 'Scorte Basse',
    'products.addToCart': 'Aggiungi al Carrello',
    'products.viewDetails': 'Visualizza Dettagli',
    'products.quickView': 'Anteprima Rapida',
    'products.noProducts': 'Nessun prodotto trovato',
    'products.clearFilters': 'Rimuovi Filtri',
    'products.priceRange': 'Fascia di Prezzo',
    'products.color': 'Colore',
    'products.storage': 'Memoria',
    'products.ram': 'RAM',
    'products.category': 'Categoria',
    'products.brand': 'Marchio',
    'products.specifications': 'Specifiche',
    'products.description': 'Descrizione',
    'products.relatedProducts': 'Prodotti Correlati',
    'products.sku': 'SKU',
    'products.warranty': 'Garanzia',
    'products.months': 'mesi',
    'products.month': 'Mese',
    'products.loginToViewPrice': 'Accedi per vedere il prezzo',
    'products.fastDelivery': 'Consegna Veloce',
    'products.securePayment': 'Pagamento Sicuro',
    'products.easyReturns': 'Resi Facili',
    'products.signInForPricing': 'Accedi per vedere prezzi esclusivi e offerte',
    'products.loginToBuy': 'Accedi per Acquistare',
    
    // Categories
    'categories.title': 'Categorie',
    'categories.shopBy': 'Acquista per Categoria',
    'categories.subtitle': 'Trova esattamente quello che cerchi',
    'categories.productsCount': 'prodotti',
    
    // Brands
    'brands.title': 'Marchi',
    'brands.shopBy': 'Acquista per Marchio',
    'brands.subtitle': 'Esplora prodotti dei migliori marchi',
    'brands.viewAll': 'Visualizza Tutti i Marchi',
    
    // Cart
    'cart.title': 'Carrello',
    'cart.empty': 'Il tuo carrello è vuoto',
    'cart.continueShopping': 'Continua gli Acquisti',
    'cart.subtotal': 'Subtotale',
    'cart.tax': 'Tassa',
    'cart.shipping': 'Spedizione',
    'cart.total': 'Totale',
    'cart.checkout': 'Procedi al Checkout',
    'cart.remove': 'Rimuovi',
    'cart.quantity': 'Quantità',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.shipping': 'Informazioni di Spedizione',
    'checkout.billing': 'Informazioni di Fatturazione',
    'checkout.payment': 'Metodo di Pagamento',
    'checkout.review': 'Rivedi Ordine',
    'checkout.sameAsBilling': 'Uguale all\'indirizzo di fatturazione',
    'checkout.placeOrder': 'Invia Ordine',
    'checkout.orderNotes': 'Note dell\'Ordine',
    'checkout.firstName': 'Nome',
    'checkout.lastName': 'Cognome',
    'checkout.email': 'Email',
    'checkout.phone': 'Telefono',
    'checkout.company': 'Azienda (Opzionale)',
    'checkout.address': 'Indirizzo',
    'checkout.addressLine2': 'Appartamento, suite, ecc.',
    'checkout.city': 'Città',
    'checkout.state': 'Stato/Provincia',
    'checkout.postalCode': 'Codice Postale',
    'checkout.country': 'Paese',
    'checkout.creditCard': 'Carta di Credito',
    'checkout.paypal': 'PayPal',
    'checkout.bankTransfer': 'Bonifico Bancario',
    'checkout.orderSummary': 'Riepilogo Ordine',
    'checkout.contactInformation': 'Informazioni di Contatto',
    'checkout.addressLine1': 'Riga Indirizzo 1',
    'checkout.addressLine2Optional': 'Riga Indirizzo 2 (Opzionale)',
    'checkout.taxVat': 'Imposta (IVA)',
    'checkout.phoneOptional': 'Telefono (Opzionale)',
    'checkout.stateOptional': 'Stato/Provincia (Opzionale)',
    'checkout.billingAddress': 'Indirizzo di Fatturazione',
    'checkout.shippingAddress': 'Indirizzo di Spedizione',
    'checkout.sameAsShipping': 'Uguale all\'indirizzo di spedizione',
    
    // Orders
    'orders.title': 'I Miei Ordini',
    'orders.track': 'Traccia Ordine',
    'orders.orderNumber': 'Numero Ordine',
    'orders.date': 'Data',
    'orders.status': 'Stato',
    'orders.total': 'Totale',
    'orders.details': 'Visualizza Dettagli',
    'orders.trackPlaceholder': 'Inserisci il tuo numero d\'ordine',
    'orders.emailPlaceholder': 'Inserisci la tua email',
    'orders.trackButton': 'Traccia Ordine',
    'orders.noOrders': 'Nessun ordine trovato',
    'orders.search': 'Cerca ordini...',
    'orders.allStatus': 'Tutti gli Stati',
    'orders.placedOn': 'Effettuato il',
    'orders.items': 'articolo/i',
    'orders.startShopping': 'Inizia a Fare Acquisti',
    'orders.tryAdjusting': 'Prova ad aggiustare la tua ricerca o i filtri',
    'orders.noOrdersYet': 'Non hai ancora effettuato nessun ordine',
    
    // Order Status
    'status.pending': 'In Attesa',
    'status.processing': 'In Elaborazione',
    'status.shipped': 'Spedito',
    'status.delivered': 'Consegnato',
    'status.cancelled': 'Annullato',
    
    // Payment Status
    'payment.pending': 'Pagamento in Attesa',
    'payment.paid': 'Pagato',
    'payment.failed': 'Pagamento Fallito',
    'payment.refunded': 'Rimborsato',
    
    // Account
    'account.title': 'Il Mio Account',
    'account.profile': 'Profilo',
    'account.settings': 'Impostazioni',
    'account.profileInformation': 'Informazioni del Profilo',
    'account.editProfile': 'Modifica Profilo',
    'account.saveChanges': 'Salva Modifiche',
    'account.cancel': 'Annulla',
    'account.verifiedAccount': 'Account Verificato',
    'account.firstName': 'Nome',
    'account.lastName': 'Cognome',
    'account.email': 'Indirizzo Email',
    'account.phone': 'Numero di Telefono',
    'account.notProvided': 'Non fornito',
    'account.myOrders': 'I Miei Ordini',
    'account.trackOrders': 'Traccia e gestisci i tuoi ordini',
    'account.addresses': 'Indirizzi',
    'account.manageAddresses': 'Gestisci indirizzi di consegna',
    'account.accountSettings': 'Impostazioni Account',
    'account.preferences': 'Preferenze e sicurezza dell\'account',
    'account.signOut': 'Esci',
    'account.logoutDescription': 'Esci dal tuo account',
    'account.viewOrders': 'Visualizza i tuoi ordini',
    'account.signInToView': 'Accedi per vedere la cronologia degli ordini e tracciare le spedizioni',
    'account.signInToAccount': 'Accedi al tuo account',
    'account.accessAccount': 'Accedi ai tuoi ordini, lista desideri e impostazioni account',
    'account.createAccount': 'Crea Account',
    'account.signInRequired': 'Accesso richiesto',
    
    // Addresses
    'addresses.title': 'I Miei Indirizzi',
    'addresses.subtitle': 'Gestisci i tuoi indirizzi di consegna',
    'addresses.addNew': 'Aggiungi Indirizzo',
    'addresses.edit': 'Modifica Indirizzo',
    'addresses.name': 'Nome Indirizzo',
    'addresses.namePlaceholder': 'es: Casa, Ufficio',
    'addresses.street': 'Indirizzo',
    'addresses.streetPlaceholder': 'Inserisci l\'indirizzo',
    'addresses.city': 'Città',
    'addresses.cityPlaceholder': 'Inserisci la città',
    'addresses.postalCode': 'Codice Postale',
    'addresses.postalCodePlaceholder': 'Inserisci il codice postale',
    'addresses.country': 'Paese',
    'addresses.countryPlaceholder': 'Inserisci il paese',
    'addresses.selectCountry': 'Seleziona paese',
    'addresses.state': 'Stato/Regione',
    'addresses.selectState': 'Seleziona stato/regione',
    'addresses.selectCity': 'Seleziona città',
    'addresses.default': 'Predefinito',
    'addresses.setDefault': 'Imposta come predefinito',
    'addresses.noAddresses': 'Nessun indirizzo salvato',
    'addresses.noAddressesDesc': 'Aggiungi il tuo primo indirizzo di consegna per velocizzare il checkout.',
    'addresses.addFirst': 'Aggiungi il tuo primo indirizzo',
    'addresses.updated': 'Indirizzo aggiornato',
    'addresses.updatedDesc': 'Il tuo indirizzo è stato aggiornato con successo.',
    'addresses.added': 'Indirizzo aggiunto',
    'addresses.addedDesc': 'Il tuo nuovo indirizzo è stato salvato.',
    'addresses.deleted': 'Indirizzo eliminato',
    'addresses.deletedDesc': 'Il tuo indirizzo è stato rimosso.',
    'addresses.defaultSet': 'Indirizzo predefinito impostato',
    'addresses.defaultSetDesc': 'Questo indirizzo verrà utilizzato come indirizzo di consegna predefinito.',
    'addresses.deleteConfirm': 'Eliminare questo indirizzo?',
    'addresses.deleteConfirmDesc': 'Questa azione non può essere annullata.',
    
    // Settings
    'settings.title': 'Impostazioni Account',
    'settings.subtitle': 'Gestisci le preferenze del tuo account',
    'settings.changePassword': 'Cambia Password',
    'settings.changePasswordDesc': 'Aggiorna la tua password per mantenere il tuo account sicuro.',
    'settings.currentPassword': 'Password Attuale',
    'settings.newPassword': 'Nuova Password',
    'settings.confirmPassword': 'Conferma Nuova Password',
    'settings.updatePassword': 'Aggiorna Password',
    'settings.passwordChanged': 'Password cambiata',
    'settings.passwordChangedDesc': 'La tua password è stata aggiornata con successo.',
    'settings.passwordMismatch': 'Le password non corrispondono',
    'settings.passwordMismatchDesc': 'Assicurati che le password corrispondano.',
    'settings.passwordTooShort': 'Password troppo corta',
    'settings.passwordTooShortDesc': 'La password deve contenere almeno 8 caratteri.',
    'settings.notifications': 'Notifiche',
    'settings.notificationsDesc': 'Scegli quali notifiche ricevere.',
    'settings.orderUpdates': 'Aggiornamenti Ordini',
    'settings.orderUpdatesDesc': 'Ricevi notifiche sullo stato dei tuoi ordini.',
    'settings.promotions': 'Promozioni',
    'settings.promotionsDesc': 'Ricevi offerte promozionali e sconti.',
    'settings.newsletter': 'Newsletter',
    'settings.newsletterDesc': 'Resta aggiornato con le nostre ultime notizie.',
    'settings.language': 'Lingua',
    'settings.languageDesc': 'Scegli la tua lingua preferita.',
    'settings.dangerZone': 'Zona Pericolosa',
    'settings.dangerZoneDesc': 'Azioni irreversibili per il tuo account.',
    'settings.deleteAccount': 'Elimina Account',
    'settings.deleteConfirm': 'Sei sicuro?',
    'settings.deleteConfirmDesc': 'Questo eliminerà permanentemente il tuo account e tutti i dati associati. Questa azione non può essere annullata.',
    'settings.accountDeleted': 'Account eliminato',
    'settings.accountDeletedDesc': 'Il tuo account è stato eliminato permanentemente.',
    
    // Auth
    'auth.login': 'Accedi',
    'auth.register': 'Crea Account',
    'auth.createAccount': 'Crea Account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Conferma Password',
    'auth.forgotPassword': 'Password Dimenticata?',
    'auth.noAccount': 'Non hai un account?',
    'auth.hasAccount': 'Hai già un account?',
    'auth.welcomeBack': 'Bentornato',
    'auth.loginSubtitle': 'Accedi al tuo account per continuare gli acquisti',
    'auth.registerSubtitle': 'Unisciti a TeleTrade Hub e inizia a fare acquisti',
    'auth.loginSuccess': 'Accesso riuscito!',
    'auth.loginFailed': 'Accesso fallito. Riprova.',
    'auth.registerSuccess': 'Account creato con successo!',
    'auth.registerFailed': 'Registrazione fallita. Riprova.',
    'auth.emailPlaceholder': 'tuo@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.fullName': 'Nome Completo',
    'auth.fullNamePlaceholder': 'Mario Rossi',
    'auth.phone': 'Telefono',
    'auth.phonePlaceholder': '+39 123 456 7890',
    'auth.rememberMe': 'Ricordami',
    'auth.passwordRequirements': 'Requisiti della password:',
    'auth.passwordMinLength': 'Almeno 8 caratteri',
    'auth.passwordUppercase': 'Una lettera maiuscola',
    'auth.passwordLowercase': 'Una lettera minuscola',
    'auth.passwordNumber': 'Un numero',
    'auth.passwordSpecial': 'Un carattere speciale',
    
    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Si è verificato un errore',
    'common.retry': 'Riprova',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.view': 'Visualizza',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.previous': 'Precedente',
    'common.search': 'Cerca',
    'common.close': 'Chiudi',
    'common.yes': 'Sì',
    'common.no': 'No',
    'common.viewAll': 'Visualizza Tutto',
    'common.optional': '(Opzionale)',
    
    // Home
    'home.productsAvailable': 'Prodotti Disponibili',
    'home.topBrands': 'Marchi Top',
    'home.customerSupport': 'Supporto Clienti',
    'home.securePayments': 'Pagamenti Sicuri',
    'home.ctaTitle': 'Pronto ad aggiornare la tua tecnologia?',
    'home.ctaSubtitle': 'Sfoglia la nostra vasta collezione di prodotti di telecomunicazioni premium dei migliori marchi mondiali.',
    'home.startShopping': 'Inizia a Fare Acquisti',
    
    // Footer
    'footer.about': 'Chi Siamo',
    'footer.contact': 'Contatto',
    'footer.howToBuy': 'Come Acquistare',
    'footer.shipping': 'Politica di Spedizione',
    'footer.returns': 'Politica di Reso',
    'footer.terms': 'Termini e Condizioni',
    'footer.privacy': 'Politica sulla Privacy',
    'footer.copyright': '© 2026 TeleTrade Hub. Tutti i diritti riservati.',
    'footer.description': 'Il tuo partner affidabile per prodotti di telecomunicazioni premium. Dispositivi di qualità dei migliori marchi mondiali.',
    'footer.company': 'Azienda',
    'footer.policies': 'Politiche',
    'footer.secureCheckout': 'Checkout Sicuro',
    'footer.safePayment': 'Pagamento Sicuro',
    'footer.fastDelivery': 'Consegna Veloce',
  },
  sk: {
    // Navigation
    'nav.home': 'Domov',
    'nav.products': 'Produkty',
    'nav.categories': 'Kategórie',
    'nav.brands': 'Značky',
    'nav.cart': 'Košík',
    'nav.account': 'Účet',
    'nav.login': 'Prihlásiť sa',
    'nav.register': 'Registrovať sa',
    'nav.logout': 'Odhlásiť sa',
    'nav.myOrders': 'Moje Objednávky',
    'nav.trackOrder': 'Sledovať Objednávku',
    'nav.signIn': 'Prihlásiť sa',
    
    // Hero
    'hero.title': 'Prémiové Telekomunikačné Produkty',
    'hero.subtitle': 'Objavte najnovšie smartfóny, tablety a príslušenstvo od top značiek',
    'hero.cta': 'Nakúpiť Teraz',
    'hero.secondary': 'Zobraziť Kategórie',
    'hero.newArrivals': 'Nové Príchody Dostupné',
    'hero.freeShipping': 'Doprava Zdarma',
    'hero.warranty': '2-Ročná Záruka',
    'hero.securePayment': 'Bezpečná Platba',
    'hero.support': 'Podpora 24/7',
    
    // Products
    'products.title': 'Produkty',
    'products.featured': 'Odporúčané Produkty',
    'products.featuredSubtitle': 'Naše top výbery',
    'products.viewAll': 'Zobraziť Všetky Produkty',
    'products.all': 'Všetky Produkty',
    'products.search': 'Hľadať produkty...',
    'products.filter': 'Filtrovať',
    'products.sort': 'Zoradiť podľa',
    'products.sortPrice': 'Cena',
    'products.sortName': 'Názov',
    'products.sortNewest': 'Najnovšie',
    'products.asc': 'Od Najnižšej',
    'products.desc': 'Od Najvyššej',
    'products.inStock': 'Skladom',
    'products.outOfStock': 'Vypredané',
    'products.lowStock': 'Nízky Sklad',
    'products.addToCart': 'Pridať do Košíka',
    'products.viewDetails': 'Zobraziť Detaily',
    'products.quickView': 'Rýchly Náhľad',
    'products.noProducts': 'Žiadne produkty nenájdené',
    'products.clearFilters': 'Vymazať Filtre',
    'products.priceRange': 'Cenové Rozpätie',
    'products.color': 'Farba',
    'products.storage': 'Úložisko',
    'products.ram': 'RAM',
    'products.category': 'Kategória',
    'products.brand': 'Značka',
    'products.specifications': 'Špecifikácie',
    'products.description': 'Popis',
    'products.relatedProducts': 'Súvisiace Produkty',
    'products.sku': 'SKU',
    'products.warranty': 'Záruka',
    'products.months': 'mesiacov',
    'products.month': 'Mesiac',
    'products.loginToViewPrice': 'Prihláste sa pre zobrazenie ceny',
    'products.fastDelivery': 'Rýchla Doprava',
    'products.securePayment': 'Bezpečná Platba',
    'products.easyReturns': 'Jednoduché Vrátenia',
    'products.signInForPricing': 'Prihláste sa pre exkluzívne ceny a ponuky',
    'products.loginToBuy': 'Prihlásiť sa na Nákup',
    
    // Categories
    'categories.title': 'Kategórie',
    'categories.shopBy': 'Nakúpiť podľa Kategórie',
    'categories.subtitle': 'Nájdite presne to, čo hľadáte',
    'categories.productsCount': 'produktov',
    
    // Brands
    'brands.title': 'Značky',
    'brands.shopBy': 'Nakúpiť podľa Značky',
    'brands.subtitle': 'Preskúmajte produkty od top značiek',
    'brands.viewAll': 'Zobraziť Všetky Značky',
    
    // Cart
    'cart.title': 'Nákupný Košík',
    'cart.empty': 'Váš košík je prázdny',
    'cart.continueShopping': 'Pokračovať v Nákupe',
    'cart.subtotal': 'Medzisúčet',
    'cart.tax': 'Daň',
    'cart.shipping': 'Doprava',
    'cart.total': 'Celkom',
    'cart.checkout': 'Pokračovať k Pokladni',
    'cart.remove': 'Odstrániť',
    'cart.quantity': 'Množstvo',
    
    // Checkout
    'checkout.title': 'Pokladňa',
    'checkout.shipping': 'Dodacie Informácie',
    'checkout.billing': 'Fakturačné Informácie',
    'checkout.payment': 'Spôsob Platby',
    'checkout.review': 'Skontrolovať Objednávku',
    'checkout.sameAsBilling': 'Rovnaké ako fakturačná adresa',
    'checkout.placeOrder': 'Odoslať Objednávku',
    'checkout.orderNotes': 'Poznámky k Objednávke',
    'checkout.firstName': 'Meno',
    'checkout.lastName': 'Priezvisko',
    'checkout.email': 'Email',
    'checkout.phone': 'Telefón',
    'checkout.company': 'Spoločnosť (Voliteľné)',
    'checkout.address': 'Adresa',
    'checkout.addressLine2': 'Byt, bytová jednotka, atď.',
    'checkout.city': 'Mesto',
    'checkout.state': 'Kraj/Provincia',
    'checkout.postalCode': 'PSČ',
    'checkout.country': 'Krajina',
    'checkout.creditCard': 'Kreditná Karta',
    'checkout.paypal': 'PayPal',
    'checkout.bankTransfer': 'Bankový Prevod',
    'checkout.orderSummary': 'Súhrn Objednávky',
    'checkout.contactInformation': 'Kontaktné Informácie',
    'checkout.addressLine1': 'Adresný Riadok 1',
    'checkout.addressLine2Optional': 'Adresný Riadok 2 (Voliteľné)',
    'checkout.taxVat': 'Daň (DPH)',
    'checkout.phoneOptional': 'Telefón (Voliteľné)',
    'checkout.stateOptional': 'Kraj/Provincia (Voliteľné)',
    'checkout.billingAddress': 'Fakturačná Adresa',
    'checkout.shippingAddress': 'Dodacia Adresa',
    'checkout.sameAsShipping': 'Rovnaké ako dodacia adresa',
    
    // Orders
    'orders.title': 'Moje Objednávky',
    'orders.track': 'Sledovať Objednávku',
    'orders.orderNumber': 'Číslo Objednávky',
    'orders.date': 'Dátum',
    'orders.status': 'Stav',
    'orders.total': 'Celkom',
    'orders.details': 'Zobraziť Detaily',
    'orders.trackPlaceholder': 'Zadajte číslo objednávky',
    'orders.emailPlaceholder': 'Zadajte váš email',
    'orders.trackButton': 'Sledovať Objednávku',
    'orders.noOrders': 'Žiadne objednávky nenájdené',
    'orders.search': 'Hľadať objednávky...',
    'orders.allStatus': 'Všetky Stavy',
    'orders.placedOn': 'Umiestnená',
    'orders.items': 'položka/položky',
    'orders.startShopping': 'Začať Nakupovať',
    'orders.tryAdjusting': 'Skúste upraviť vyhľadávanie alebo filtre',
    'orders.noOrdersYet': 'Ešte ste neumiestnili žiadnu objednávku',
    
    // Order Status
    'status.pending': 'Čakajúce',
    'status.processing': 'Spracováva sa',
    'status.shipped': 'Odoslané',
    'status.delivered': 'Doručené',
    'status.cancelled': 'Zrušené',
    
    // Payment Status
    'payment.pending': 'Platba Čaká',
    'payment.paid': 'Zaplatené',
    'payment.failed': 'Platba Zlyhala',
    'payment.refunded': 'Vrátené',
    
    // Account
    'account.title': 'Môj Účet',
    'account.profile': 'Profil',
    'account.settings': 'Nastavenia',
    'account.profileInformation': 'Informácie o Profile',
    'account.editProfile': 'Upraviť Profil',
    'account.saveChanges': 'Uložiť Zmeny',
    'account.cancel': 'Zrušiť',
    'account.verifiedAccount': 'Overený Účet',
    'account.firstName': 'Meno',
    'account.lastName': 'Priezvisko',
    'account.email': 'Emailová Adresa',
    'account.phone': 'Telefónne Číslo',
    'account.notProvided': 'Neposkytnuté',
    'account.myOrders': 'Moje Objednávky',
    'account.trackOrders': 'Sledovať a spravovať vaše objednávky',
    'account.addresses': 'Adresy',
    'account.manageAddresses': 'Spravovať dodacie adresy',
    'account.accountSettings': 'Nastavenia Účtu',
    'account.preferences': 'Predvoľby a bezpečnosť účtu',
    'account.signOut': 'Odhlásiť sa',
    'account.logoutDescription': 'Odhlásiť sa z vášho účtu',
    'account.viewOrders': 'Zobraziť vaše objednávky',
    'account.signInToView': 'Prihláste sa pre zobrazenie histórie objednávok a sledovanie zásielok',
    'account.signInToAccount': 'Prihlásiť sa do vášho účtu',
    'account.accessAccount': 'Prístup k vašim objednávkam, zoznamu prianí a nastaveniam účtu',
    'account.createAccount': 'Vytvoriť Účet',
    'account.signInRequired': 'Vyžaduje sa prihlásenie',
    
    // Addresses
    'addresses.title': 'Moje Adresy',
    'addresses.subtitle': 'Spravovať vaše dodacie adresy',
    'addresses.addNew': 'Pridať Adresu',
    'addresses.edit': 'Upraviť Adresu',
    'addresses.name': 'Názov Adresy',
    'addresses.namePlaceholder': 'napr. Domov, Kancelária',
    'addresses.street': 'Ulica',
    'addresses.streetPlaceholder': 'Zadajte adresu',
    'addresses.city': 'Mesto',
    'addresses.cityPlaceholder': 'Zadajte mesto',
    'addresses.postalCode': 'PSČ',
    'addresses.postalCodePlaceholder': 'Zadajte PSČ',
    'addresses.country': 'Krajina',
    'addresses.countryPlaceholder': 'Zadajte krajinu',
    'addresses.selectCountry': 'Vybrať krajinu',
    'addresses.state': 'Kraj/Región',
    'addresses.selectState': 'Vybrať kraj/región',
    'addresses.selectCity': 'Vybrať mesto',
    'addresses.default': 'Predvolené',
    'addresses.setDefault': 'Nastaviť ako predvolené',
    'addresses.noAddresses': 'Žiadne adresy uložené',
    'addresses.noAddressesDesc': 'Pridajte svoju prvú dodaciu adresu pre rýchlejší checkout.',
    'addresses.addFirst': 'Pridať vašu prvú adresu',
    'addresses.updated': 'Adresa aktualizovaná',
    'addresses.updatedDesc': 'Vaša adresa bola úspešne aktualizovaná.',
    'addresses.added': 'Adresa pridaná',
    'addresses.addedDesc': 'Vaša nová adresa bola uložená.',
    'addresses.deleted': 'Adresa odstránená',
    'addresses.deletedDesc': 'Vaša adresa bola odstránená.',
    'addresses.defaultSet': 'Predvolená adresa nastavená',
    'addresses.defaultSetDesc': 'Táto adresa bude použitá ako vaša predvolená dodacia adresa.',
    'addresses.deleteConfirm': 'Odstrániť túto adresu?',
    'addresses.deleteConfirmDesc': 'Táto akcia sa nedá vrátiť späť.',
    
    // Settings
    'settings.title': 'Nastavenia Účtu',
    'settings.subtitle': 'Spravovať predvoľby vášho účtu',
    'settings.changePassword': 'Zmeniť Heslo',
    'settings.changePasswordDesc': 'Aktualizujte svoje heslo pre zabezpečenie vášho účtu.',
    'settings.currentPassword': 'Súčasné Heslo',
    'settings.newPassword': 'Nové Heslo',
    'settings.confirmPassword': 'Potvrdiť Nové Heslo',
    'settings.updatePassword': 'Aktualizovať Heslo',
    'settings.passwordChanged': 'Heslo zmenené',
    'settings.passwordChangedDesc': 'Vaše heslo bolo úspešne aktualizované.',
    'settings.passwordMismatch': 'Heslá sa nezhodujú',
    'settings.passwordMismatchDesc': 'Uistite sa, že sa heslá zhodujú.',
    'settings.passwordTooShort': 'Heslo príliš krátke',
    'settings.passwordTooShortDesc': 'Heslo musí mať aspoň 8 znakov.',
    'settings.notifications': 'Notifikácie',
    'settings.notificationsDesc': 'Vyberte, aké notifikácie chcete dostávať.',
    'settings.orderUpdates': 'Aktualizácie Objednávok',
    'settings.orderUpdatesDesc': 'Dostávajte upozornenia o stave vašich objednávok.',
    'settings.promotions': 'Propagácie',
    'settings.promotionsDesc': 'Dostávajte propagačné ponuky a zľavy.',
    'settings.newsletter': 'Newsletter',
    'settings.newsletterDesc': 'Zostaňte informovaní o našich najnovších novinkách.',
    'settings.language': 'Jazyk',
    'settings.languageDesc': 'Vyberte váš preferovaný jazyk.',
    'settings.dangerZone': 'Nebezpečná Zóna',
    'settings.dangerZoneDesc': 'Nevratné akcie pre váš účet.',
    'settings.deleteAccount': 'Zmazať Účet',
    'settings.deleteConfirm': 'Ste si istí?',
    'settings.deleteConfirmDesc': 'Toto natrvalo zmaže váš účet a všetky súvisiace dáta. Táto akcia sa nedá vrátiť späť.',
    'settings.accountDeleted': 'Účet zmazaný',
    'settings.accountDeletedDesc': 'Váš účet bol natrvalo zmazaný.',
    
    // Auth
    'auth.login': 'Prihlásiť sa',
    'auth.register': 'Vytvoriť Účet',
    'auth.createAccount': 'Vytvoriť Účet',
    'auth.email': 'Email',
    'auth.password': 'Heslo',
    'auth.confirmPassword': 'Potvrdiť Heslo',
    'auth.forgotPassword': 'Zabudli ste Heslo?',
    'auth.noAccount': 'Nemáte účet?',
    'auth.hasAccount': 'Už máte účet?',
    'auth.welcomeBack': 'Vitajte Späť',
    'auth.loginSubtitle': 'Prihláste sa do svojho účtu pre pokračovanie v nákupe',
    'auth.registerSubtitle': 'Pripojte sa k TeleTrade Hub a začnite nakupovať',
    'auth.loginSuccess': 'Prihlásenie úspešné!',
    'auth.loginFailed': 'Prihlásenie zlyhalo. Skúste to znova.',
    'auth.registerSuccess': 'Účet úspešne vytvorený!',
    'auth.registerFailed': 'Registrácia zlyhala. Skúste to znova.',
    'auth.emailPlaceholder': 'vas@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.fullName': 'Celé Meno',
    'auth.fullNamePlaceholder': 'Ján Novák',
    'auth.phone': 'Telefón',
    'auth.phonePlaceholder': '+421 123 456 789',
    'auth.rememberMe': 'Zapamätať si ma',
    'auth.passwordRequirements': 'Požiadavky na heslo:',
    'auth.passwordMinLength': 'Aspoň 8 znakov',
    'auth.passwordUppercase': 'Jedno veľké písmeno',
    'auth.passwordLowercase': 'Jedno malé písmeno',
    'auth.passwordNumber': 'Jedno číslo',
    'auth.passwordSpecial': 'Jeden špeciálny znak',
    
    // Common
    'common.loading': 'Načítava sa...',
    'common.error': 'Vyskytla sa chyba',
    'common.retry': 'Skúsiť Znova',
    'common.save': 'Uložiť',
    'common.cancel': 'Zrušiť',
    'common.delete': 'Zmazať',
    'common.edit': 'Upraviť',
    'common.view': 'Zobraziť',
    'common.back': 'Späť',
    'common.next': 'Ďalej',
    'common.previous': 'Predchádzajúce',
    'common.search': 'Hľadať',
    'common.close': 'Zavrieť',
    'common.yes': 'Áno',
    'common.no': 'Nie',
    'common.viewAll': 'Zobraziť Všetko',
    'common.optional': '(Voliteľné)',
    
    // Home
    'home.productsAvailable': 'Produkty Dostupné',
    'home.topBrands': 'Top Značky',
    'home.customerSupport': 'Zákaznícka Podpora',
    'home.support': 'Podpora Dostupná',
    'home.authenticProducts': 'Autentické Produkty',
    'home.securePayments': 'Bezpečné Platby',
    'home.ctaTitle': 'Pripravení vylepšiť vašu technológiu?',
    'home.ctaSubtitle': 'Prehľadajte našu rozsiahlu kolekciu prémiových telekomunikačných produktov od popredných svetových značiek.',
    'home.startShopping': 'Začať Nakupovať',
    
    // Footer
    'footer.about': 'O Nás',
    'footer.contact': 'Kontakt',
    'footer.howToBuy': 'Ako Nakúpiť',
    'footer.shipping': 'Politika Dopravy',
    'footer.returns': 'Politika Vrátenia',
    'footer.terms': 'Obchodné Podmienky',
    'footer.privacy': 'Politika Súkromia',
    'footer.copyright': '© 2026 TeleTrade Hub. Všetky práva vyhradené.',
    'footer.description': 'Váš dôveryhodný partner pre prémiové telekomunikačné produkty. Kvalitné zariadenia od popredných svetových značiek.',
    'footer.company': 'Spoločnosť',
    'footer.policies': 'Politiky',
    'footer.secureCheckout': 'Bezpečný Checkout',
    'footer.safePayment': 'Bezpečná Platba',
    'footer.fastDelivery': 'Rýchla Doprava',
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

const LANGUAGE_KEY = 'teletrade_language';

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    if (typeof window === 'undefined') return;
    
    const validLanguages: Language[] = ['en', 'de', 'fr', 'es', 'it', 'sk'];
    
    // Check URL params first (highest priority)
    const params = new URLSearchParams(window.location.search);
    const urlLang = params.get('lang') as Language;
    if (urlLang && validLanguages.includes(urlLang)) {
      setLanguageState(urlLang);
      localStorage.setItem(LANGUAGE_KEY, urlLang);
      localStorage.setItem('language', urlLang); // Sync for API client
      return;
    }
    
    // Check localStorage
    const savedLang = localStorage.getItem(LANGUAGE_KEY) as Language;
    if (savedLang && validLanguages.includes(savedLang)) {
      setLanguageState(savedLang);
      localStorage.setItem('language', savedLang); // Sync for API client
      // Update URL if not already set
      if (!urlLang) {
        const url = new URL(window.location.href);
        if (savedLang !== 'en') {
          url.searchParams.set('lang', savedLang);
        }
        window.history.replaceState({}, '', url.toString());
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem(LANGUAGE_KEY, lang);
      // Also sync to 'language' key for API client compatibility
      localStorage.setItem('language', lang);
      
      // Update URL without reload - preserve current path
      const url = new URL(window.location.href);
      if (lang === 'en') {
        url.searchParams.delete('lang');
      } else {
        url.searchParams.set('lang', lang);
      }
      window.history.replaceState({}, '', url.toString());
      
      // Reload page to apply language to server components
      window.location.reload();
    }
  };

  const t = (key: string): string => {
    // Try current language first
    const langTranslations = translations[language];
    if (langTranslations && langTranslations[key]) {
      return langTranslations[key];
    }
    // Fallback to English for missing languages or missing keys
    if (language !== 'en' && translations.en[key]) {
      return translations.en[key];
    }
    // Return key if no translation found
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

